config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.ics.muni.cz/perun/perun-idm/perun:
      branch: main
      repo: https://gitlab.ics.muni.cz/perun/perun-idm/perun.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.ics.muni.cz/perun/perun-idm/perun git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-jade-lobster.sh
        container: qc.acc_skinny-sapphire-jellyfish
  QC.Doc:
    repos:
      gitlab.ics.muni.cz/perun/perun-idm/perun find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-seashell-owl.sh
        container: qc.doc_gimpy-champagne-weasel
      gitlab.ics.muni.cz/perun/perun-idm/perun git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-bistre-centipede.sh
        container: qc.doc_gloppy-lavender-crab
      gitlab.ics.muni.cz/perun/perun-idm/perun markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-peach-wolverine.sh
        container: qc.doc_foggy-lavender-impala
  QC.Lic:
    repos:
      gitlab.ics.muni.cz/perun/perun-idm/perun licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-copper-bordeaux.sh
        container: qc.lic_stuffy-amethyst-wildebeest
  QC.Sec:
    repos:
      gitlab.ics.muni.cz/perun/perun-idm/perun bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-magenta-barb.sh
        container: qc.sec_flimsy-buff-stoat
  QC.Sty:
    repos:
      gitlab.ics.muni.cz/perun/perun-idm/perun checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-asparagus-bracke.sh
        container: qc.sty_cozy-crimson-hedgehog
      gitlab.ics.muni.cz/perun/perun-idm/perun flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-asparagus-eleuth.sh
        container: qc.sty_trippy-peach-fish
      gitlab.ics.muni.cz/perun/perun-idm/perun hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-burgundy-quail.sh
        container: qc.sty_sloppy-lime-gharial
      gitlab.ics.muni.cz/perun/perun-idm/perun jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-azure-chinchilla.sh
        container: qc.sty_surly-teal-hare
  QC.Uni:
    repos:
      gitlab.ics.muni.cz/perun/perun-idm/perun pytest:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-periwinkle-magpie.sh
        container: qc.uni_grumpy-azure-gorilla
  QC.Ver:
    repos:
      gitlab.ics.muni.cz/perun/perun-idm/perun get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-silver-mongoose.sh
        container: qc.ver_sleazy-green-squirrel
timeout: 5400
